# Site settings
title: Results Now
tagline: "Far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics"
url: "https://resultsnowfitness.net" # The base hostname & protocol for your site. Use it if you need absolute URL's
description: ""
future: true

# Social
socialimg: /img/social.jpg # be sure to change this image
facebook: ResultsNowLLC
twitter: twusername
instagram: igusername

# Contact
phone: "1-859-334-0249"
email: "resultsnowllc@gmail.com"
street1: "1597 Cavalry Drive"
city: "Union"
state: "KY"
zipcode: "41091"

ifttt:
    key: czK6TzHRYCPhTdiXzioxb7
    contact_event: contact_resultsnow
    mailer_event: resultsnow_mailer

# Use this for production
sass:
    sass_dir: _sass
    style: compact

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
