# Site settings
title: Results Now
tagline: "We are a Fit Family that enjoys helping others. We motivate each other and encourage each other. Our instructors and trainers are certified and can modify all exercises to any fitness level. We enjoy training and helping people achieve their fitness goals. We are here for you!!! Let us help you get to your goal!!"
url: "https://resultsnowfitness.net" # The base hostname & protocol for your site. Use it if you need absolute URL's
description: ""
future: true

# Social
socialimg: /images/social.jpg # be sure to change this image
facebook: ResultsNowLLC
twitter: twusername
instagram: igusername

# Contact
phone: "1-859-334-0249"
email: "resultsnowllc@gmail.com"
street1: "1597 Cavalry Drive"
city: "Union"
state: "KY"
zipcode: "41091"

ifttt:
    key: czK6TzHRYCPhTdiXzioxb7
    contact_event: contact_resultsnow
    mailer_event: resultsnow_mailer

# Use this for production
sass:
    sass_dir: _sass
    style: compact

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
