- title: Strength 
  description: Single and compound muscular movements to create definition and musclular endurance.
  icon: weightlifting

- title: Cardio
  description: Enhance cardiovascular endurance and burn calories.
  icon: gym

- title: Mix of Strength & Cardio 
  description: Cardio and strength training together to help with cardiovascular and muscle endurance.
  icon: exercise-2

- title: Yoga
  description: Focus on the breath through a dynamic flow of strength and flexibility poses and then clear the mind with meditation.
  icon: meditation
