- title: Cardio Program
  description: Separated they live in Bookmarksgrove right at the coast of the Semantics
  icon: gym

- title: Body Building
  description: Separated they live in Bookmarksgrove right at the coast of the Semantics
  icon: weightlifting

- title: Karate Classes
  description: Separated they live in Bookmarksgrove right at the coast of the Semantics
  icon: martial-arts

- title: Boxing Program
  description: Separated they live in Bookmarksgrove right at the coast of the Semantics
  icon: gloves
