- title: Strength 
  description: Separated they live in Bookmarksgrove right at the coast of the Semantics
  icon: weightlifting

- title: Cardio
  description: Separated they live in Bookmarksgrove right at the coast of the Semantics
  icon: gym

- title: Mix of Strength & Cardio 
  description: Separated they live in Bookmarksgrove right at the coast of the Semantics
  icon: exercise-2

- title: Yoga
  description: Separated they live in Bookmarksgrove right at the coast of the Semantics
  icon: meditation
