- name: Kat Mueller
  specialty: Owner/Certified Personal Trainer/Certified Group Fitness Instructor
  image: IMG_6210.jpeg
  
- name: Alisa Hampton
  specialty: Certified Personal Trainer/Certified Group Fitness Instructor/Certified Yoga Instructor
  image: IMG_6202.JPG
  
- name: Daryl Perry
  specialty: Certified Personal Trainer/Certified Nutritionist
  image: daryl.JPG

- name: Ethan Goodrich
  specialty: Certified Personal Trainer
  image: IMG_5657.JPG
  
- name: Lisa Baker
  specialty: Certified Yoga Instructor
  image: Lisa profile.jpg
