- name: Kat Mueller
  specialty: Owner/Certified Personal Trainer/Certified Group Fitness Instructor
  image: Kat profile.png
  
- name: Alisa Hampton
  specialty: Certified Personal Trainer/Certified Group Fitness Instructor/Certified Yoga Instructor
  image: Alisa profile.png
  
- name: Daryl Perry
  specialty: Certified Personal Trainer/Certified Nutritionist
  image: Daryl profile.png

- name: Jimmy Mounce
  specialty: Certified Personal Trainer
  image: 

- name: Ethan Goodrich
  specialty: Certified Personal Trainer
  image: ethan.png

- name: Linda Holderness
  specialty: Certified Group Fitness Instructor
  image: Linda profile.png
  
- name: Melissa Chapman
  specialty: Certified Group Fitness Instructor
  image: Melissa profle.png
  
- name: Lisa Baker
  specialty: Certified Yoga Instructor
  image: Lisa profile.jpg
