- name: KYLE FELTNER
  specialty: Personal Trainer/Group Fitness Instructor
  image: trainer-1.jpg

- name: KAT MUELLER
  specialty: Body Building Trainer
  image: trainer-2.jpg

- name: ALYSHA REED
  specialty: Body Building Trainer
  image: trainer-3.jpg

- name: GEORGE COOPER
  specialty: Body Building Trainer
  image: trainer-4.jpg

