- name: DIEGO CARTER
  specialty: Body Building Trainer
  image: trainer-1.jpg

- name: LEA YOUNG
  specialty: Body Building Trainer
  image: trainer-2.jpg

- name: ALYSHA REED
  specialty: Body Building Trainer
  image: trainer-3.jpg

- name: GEORGE COOPER
  specialty: Body Building Trainer
  image: trainer-4.jpg

