- name: KAT MUELLER
  specialty: Owner/Certified Personal Trainer/Certified Group Fitness Instructor
  image: trainer-2.jpg
  
- name: KYLE FELTNER
  specialty: Certified Personal Trainer/Certified Group Fitness Instructor
  image: 269409_915360389921_2042785016_n.jpg
  
- name: Katie Thomas
  specialty: Certified Personal Trainer/Certified Group Fitness Instructor
  image: katie.png

- name: Ethan Goodrich
  specialty: Certified Personal Trainer
  image: ethan.png

- name: Linda Holderness
  specialty: Certified Group Fitness Instructor
  image: linda.png

- name: Lisa Baker
  specialty: Certified Yoga Instructor
  image: lisa.png
  
- name: Jenny Zurad
  specialty: Certified Yoga Instructor
  image: jenny profile.jpg
  
- name: Stephanie Grant
  specialty: Certified Yoga Instructor
  image: trainer-3.jpg
